backend: positional
env_name: ant
num_timesteps: 50000000
num_evals: 10
reward_scaling: 10
episode_length: 1000
normalize_observations: true
action_repeat: 1
unroll_length: 5
num_minibatches: 32
num_updates_per_batch: 4
discounting: 0.97
learning_rate: 3e-4
entropy_cost: 1e-2
num_envs: 4096
batch_size: 2048
seed: 1
max_y: 8000
min_y: 0