backend: positional
use_lff: false
lff_scale: 1.0
training_algo: sac
env_name: ant
num_timesteps: 6553600
num_evals: 20
reward_scaling: 30
episode_length: 1000
normalize_observations: true
action_repeat: 1
discounting: 0.997
learning_rate: 6e-4
num_envs: 128
batch_size: 512
grad_updates_per_step: 64
max_devices_per_host: 1
max_replay_size: 1048576
min_replay_size: 8192
seed: 1
max_y: 2500
min_y: 0
hidden_layer_size: 1024
reward_noise_scale: 0.0
