backend: positional
use_lff: true
lff_scale: 0.0001
training_algo: ppo
env_name: ant
num_timesteps: 50000000
num_evals: 10
reward_scaling: 10
episode_length: 1000
normalize_observations: True
action_repeat: 1
discounting: 0.99
learning_rate: 0.0003
num_envs: 2048
batch_size: 640
num_updates_per_batch: 4
unroll_length: 10
num_minibatches: 32
entropy_cost: 0.0
seed: 1
max_y: 8000
min_y: 0
hidden_layer_size: 1024
reward_noise_scale: 0.0
wandb_mode: "run"
