backend: positional
use_lff: true
lff_scale: 0.001
training_algo: sac
env_name: walker2d
num_timesteps: 7864320
num_evals: 20
reward_scaling: 5
episode_length: 1000
normalize_observations: true
action_repeat: 1
discounting: 0.997
learning_rate: 6e-4
num_envs: 128
batch_size: 128
grad_updates_per_step: 32
max_devices_per_host: 1
max_replay_size: 1048576
min_replay_size: 8192
seed: 1
max_y: 2500
min_y: 0
hidden_layer_size: 1024
wandb_mode: "run"
reward_noise_scale: 0.0
